# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a107dba2ea7ea4e5f7e834b237c35cb09359567ec614fdb7322ca06703685de6057c529666f55b347b0d5a37b31784c1e426fbf46856888e73ea1d6ca50eddf3

test:
  secret_key_base: 5f57ee906320ce4e178e8f4e07e5f1973d5ac44c143182c7fe83dadfa37693e244b6a86a7dc917bb3e9d475029ebd666a032cf411982187b32aa8368b76b9dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
